apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: algorithms.science.sneaksanddata.com
  namespace: nexus
spec:
  # REST API: /apis/science.sneaksanddata.com/<version>
  group: science.sneaksanddata.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      additionalPrinterColumns:
        - name: Registry
          type: string
          jsonPath: .spec.imageRegistry
        - name: Image
          type: string
          jsonPath: .spec.imageRepository
        - name: Version
          type: string
          jsonPath: .spec.imageTag
        - name: Timeout
          type: integer
          jsonPath: .spec.deadlineSeconds
        - name: Workgroup host
          type: string
          jsonPath: .spec.workgroupHost
        - name: Workgroup
          type: string
          jsonPath: .spec.workgroup
        - name: CPU Limit
          type: string
          jsonPath: .spec.cpuLimit
        - name: Memory Limit
          type: string
          jsonPath: .spec.memoryLimit
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                imageRegistry:
                  type: string
                  description: Container registry for image repository
                  default: esdcrdevelopment.azurecr.io
                imageRepository:
                  type: string
                  description: The image repository to use for the algorithm
                imageTag:
                  type: string
                  description: The image tag to use for the algorithm
                env:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The name of the environment variable
                      value:
                        type: string
                        description: The value of the environment variable
                      valueFrom:
                        type: object
                        properties:
                          fieldRef:
                            type: object
                            properties:
                              fieldPath:
                                type: string
                                description: The name of the field to use as the value of the environment variable
                          resourceFieldRef:
                            type: object
                            properties:
                              containerName:
                                type: string
                                description: The name of the container to use as the resource for the environment variable
                              resource:
                                type: string
                                description: The name of the resource to use as the value of the environment variable
                              divisor:
                                type: string
                                description: The divisor to use for the resource value
                          configMapKeyRef:
                            type: object
                            properties:
                              name:
                                type: string
                                description: The name of the config map to use as the value of the environment variable
                              key:
                                type: string
                                description: The key within the config map to use as the value of the environment variable
                          secretKeyRef:
                            type: object
                            properties:
                              name:
                                type: string
                                description: The name of the secret to use as the value of the environment variable
                              key:
                                type: string
                                description: The key within the secret to use as the value of the environment variable
                envFrom:
                  type: array
                  items:
                    type: object
                    properties:
                      configMapRef:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The name of the config map to use as an environment variable source
                          optional:
                            type: boolean
                            description: Whether the config map reference is optional
                      secretRef:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The name of the secret to use as an environment variable source
                          optional:
                            type: boolean
                            description: Whether the secret reference is optional
                cpuLimit:
                  type: string
                  description: The CPU limit for the job
                memoryLimit:
                  type: string
                  description: The memory limit for the job
                deadlineSeconds:
                  type: integer
                  minimum: 10
                  maximum: 604800
                  nullable: true
                  description: The deadline in seconds for the job (null to use the default deadline)
                maximumRetries:
                  type: integer
                  maximum: 512
                  nullable: true
                  description: The maximum number of retries for the job (null to use the default max retries)
                workgroupHost:
                  type: string
                  description: Hosting cluster for this workgroup. If not provided, defaults to the cluster where scheduler is deployed
                  default: ""
                workgroup:
                  type: string
                  enum: [
                    "algorithm-on-demand-amd",
                    "algorithm-on-demand-arm",
                    "algorithm-spot-amd",
                    "algorithm-spot-arm"
                  ]
                  description: The workgroup to use for the job
                additionalWorkgroups:
                  type: object
                  additionalProperties:
                    type: string
                  nullable: true
                  description: Additional workgroups to add to the job
                customResources:
                  type: object
                  additionalProperties:
                    type: string
                  nullable: true
                  description: Custom resources for the job
                monitoringParameters:
                  type: array
                  items:
                    type: string
                  description: Monitoring parameters for the job
                speculativeAttempts:
                  type: integer
                  maximum: 10
                  nullable: true
                  description: The number of speculative attempts for the job (null to use the default number of attempts)
                transientExitCodes:
                  type: array
                  items:
                    type: integer
                  default: [ ]
                  description: List of exit codes to ignore when managing pod failure
                fatalExitCodes:
                  type: array
                  items:
                    type: integer
                  default: [ ]
                  description: List of exit codes to fail the job
                command:
                  type: string
                  enum:
                    - "python"
                    - "ddtrace-run python"
                    - "dotnet"
                  default: "python"
                args:
                  type: array
                  items:
                    type: string
                  default:
                    - "main.py"
                    - "--sas-uri={0}"
                    - "--request-id={0}"
                mountDatadogSocket:
                  type: boolean
                  nullable: true
                  default: true
                  description: Set to `true` to mount unix domain socket on host for Datadog Agent
      # subresources for the custom resource
      subresources:
        # enables the status subresource
        status: {}
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/science.sneaksanddata.com/v1beta1/algorithms
    plural: algorithms
    # singular name to be used as an alias on the CLI and for display
    singular: algorithm
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: MachineLearningAlgorithm
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - mla
