apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shards.science.sneaksanddata.com
  namespace: nexus
spec:
  # REST API: /apis/science.sneaksanddata.com/<version>
  group: science.sneaksanddata.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                alias:
                  type: string
                  description: Alias for this shard's cluster name
                kubeConfigSecretRef:
                  type: object
                  description: Secret reference for the kubeconfig for this shard
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Name of the secret containing .kubeconfig entry for this shard
                schedulingEnabled:
                  type: bool
                  description: Enables or disables this shard for scheduling
                  default: true
      # subresources for the custom resource
      subresources:
        # enables the status subresource
        status: {}
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/science.sneaksanddata.com/v1beta1/algorithms
    plural: shards
    # singular name to be used as an alias on the CLI and for display
    singular: shard
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ComputeShard
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - csh
